### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by ejiyuan** [HsuanXyz/ionic3-chat#4]
Error
Close
Runtime Error
Uncaught (in promise): Error: Cannot find module '../pages/tabs/tabs.module'. Error: Cannot find module '../pages/tabs/tabs.module'. at webpackEmptyContext (http://localhost:8100/build/main.js:76294:8) at loadAndCompile (http://localhost:8100/build/main.js:75290:36) at NgModuleLoader.load (http://localhost:8100/build/main.js:75255:83) at ModuleLoader.load (http://localhost:8100/build/main.js:54758:44) at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26281:39) at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:26264:25) at getComponent (http://localhost:8100/build/main.js:29339:23) at convertToView (http://localhost:8100/build/main.js:29357:16) at convertToViews (http://localhost:8100/build/main.js:29376:32) at NavControllerBase._loadLazyLoading (http://localhost:8100/build/main.js:43086:108)
Stack
Error: Uncaught (in promise): Error: Cannot find module '../pages/tabs/tabs.module'.
Error: Cannot find module '../pages/tabs/tabs.module'.
    at webpackEmptyContext (http://localhost:8100/build/main.js:76294:8)
    at loadAndCompile (http://localhost:8100/build/main.js:75290:36)
    at NgModuleLoader.load (http://localhost:8100/build/main.js:75255:83)
    at ModuleLoader.load (http://localhost:8100/build/main.js:54758:44)
    at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26281:39)
    at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:26264:25)
    at getComponent (http://localhost:8100/build/main.js:29339:23)
    at convertToView (http://localhost:8100/build/main.js:29357:16)
    at convertToViews (http://localhost:8100/build/main.js:29376:32)
    at NavControllerBase._loadLazyLoading (http://localhost:8100/build/main.js:43086:108)
    at c (http://localhost:8100/build/polyfills.js:3:12642)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:11998)
    at NavControllerBase._fireError (http://localhost:8100/build/main.js:42996:16)
    at NavControllerBase._failed (http://localhost:8100/build/main.js:42984:14)
    at http://localhost:8100/build/main.js:43039:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8488)
    at Object.onInvoke (http://localhost:8100/build/main.js:4403:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8428)
    at r.run (http://localhost:8100/build/polyfills.js:3:3686)
    at http://localhost:8100/build/polyfills.js:3:13183
Ionic Framework: 3.2.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 7.10.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by HsuanXyz** [comment]
嗨，你好。从错误上看应该是tabs.module引入的问题，但是我重新Clone这个项目没有出现这样的错误，你可以坚持一下代码尝试找出问题吗？

**Comment by ejiyuan** [comment]
@HsuanXyz 
Ionic App Scripts 改为1.32问题不存在了，可能是Ionic App Scripts: 1.3.7有依赖问题
